name: .NET

on:
  push:
    branches: [ main, devops ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish Tryneboka.csproj -c Release -o release
    - name: Upload release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Tryneboka
        path: release/**
        if-no-files-found: error
